name: flutter_widget_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  test: ^1.17.10
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
      - asset: fonts/Roboto-Black.ttf
        weight: 900
      - asset: fonts/Roboto-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: fonts/Roboto-Bold.ttf
        weight: 700
      - asset: fonts/Roboto-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Roboto-Italic.ttf
        style: italic
      - asset: fonts/Roboto-Light.ttf
        weight: 300
      - asset: fonts/Roboto-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/Roboto-Medium.ttf
        weight: 500
      - asset: fonts/Roboto-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: fonts/Roboto-Regular.ttf
        weight: 400
      - asset: fonts/Roboto-Thin.ttf
        weight: 100
      - asset: fonts/Roboto-ThinItalic.ttf
        weight: 100
        style: italic

